//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TamazightNLU.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TamazightNLU.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work in progress.
        /// </summary>
        public static string AboutDemos {
            get {
                return ResourceManager.GetString("AboutDemos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Language Processing is a subfield of Artificial Intelligence that is concerned about the interaction between computers and human natural language”. NLP makes it possible for computers to read text, hear speech and interpret it, measure sentiment and even determine which parts are relevant. It has become really helpful resolving ambiguity in language and adds numeric structure to the data for many downstream applications..
        /// </summary>
        public static string AboutNlp {
            get {
                return ResourceManager.GetString("AboutNlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtopic of Natural Language Processing that uses AI to comprehend input made in the form of sentences in text or speech format. It enables computers to understand commands without the formalized syntax of computer languages and it also enables computers to communicate back to humans in their own languages.&lt;br/&gt;
        ///
        ///.
        /// </summary>
        public static string AboutNlu {
            get {
                return ResourceManager.GetString("AboutNlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takes audio content and transcribes it into written words in a word processor or other display destination. Extremely valuable to anyone who needs to generate a lot of written content without a lot of manual typing. It is also useful for people with disabilities that make it difficult for them to use a keyboard.&lt;br&gt;
        ///
        ///Speech-to-text may also be known as voice recognition.
        /// </summary>
        public static string AboutSpeechRecognition {
            get {
                return ResourceManager.GetString("AboutSpeechRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work in progress.
        /// </summary>
        public static string AboutSpellChecker {
            get {
                return ResourceManager.GetString("AboutSpellChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form of speech synthesis that converts text into spoken voice output. Text to speech systems were first developed to aid the visually impaired by offering a computer-generated spoken voice that would &quot;read&quot; text to the user..
        /// </summary>
        public static string AboutTextToSpeech {
            get {
                return ResourceManager.GetString("AboutTextToSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string Allrightsreserved {
            get {
                return ResourceManager.GetString("Allrightsreserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demos.
        /// </summary>
        public static string Demos {
            get {
                return ResourceManager.GetString("Demos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As artificial intelligence progresses and technology becomes more sophisticated, we expect existing concepts to embrace this change — or change themselves. Similarly, in the domain of computer-aided processing of natural languages, shall the concept of natural language processing give way to natural language understanding? Or is the relation between the two concepts subtler and more…    &lt;br/&gt; With that in mind , here we apply those technologies for Tamazight language by producing text files for stop words,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HomeText {
            get {
                return ResourceManager.GetString("HomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NLP.
        /// </summary>
        public static string NLP {
            get {
                return ResourceManager.GetString("NLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NLU.
        /// </summary>
        public static string NLU {
            get {
                return ResourceManager.GetString("NLU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Services.
        /// </summary>
        public static string OnlineServices {
            get {
                return ResourceManager.GetString("OnlineServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpeechRecognition.
        /// </summary>
        public static string SpeechRecognition {
            get {
                return ResourceManager.GetString("SpeechRecognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell checker.
        /// </summary>
        public static string SpellChecker {
            get {
                return ResourceManager.GetString("SpellChecker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string TermsandConditions {
            get {
                return ResourceManager.GetString("TermsandConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextToSpeech.
        /// </summary>
        public static string TextToSpeech {
            get {
                return ResourceManager.GetString("TextToSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View on Githut.
        /// </summary>
        public static string ViewonGithut {
            get {
                return ResourceManager.GetString("ViewonGithut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Documentation.
        /// </summary>
        public static string WelcomeHeader {
            get {
                return ResourceManager.GetString("WelcomeHeader", resourceCulture);
            }
        }
    }
}
